[theme]

# Used to style primary interface elements. It's the color displayed most frequently across your app's
# screens and components. Examples of widgets using this color are st.slider and st.checkbox.
#primaryColor = "rgba(0,180,0,1)"#"#909a2b" # green

# Background color for the main container.
backgroundColor = "rgba(248,252,248,1)" # sepia yellow

# Used as the background for most widgets. Examples of widgets with this background are st.sidebar,
# st.text_input, st.date_input.
#secondaryBackgroundColor =  "rgba(20,52,50,0.1)"#"#ebd2d9" # wheat  "#d7ab82" # yellow <-- not enough contrast

# Font color for the page.
textColor = "black"#"#6e7074" # grey

# Font family (serif | sans serif | mono) for the page. Will not impact code areas.
# Default: "sans serif"
font = "serif"
